### PR TITLE
Showing name of AAS in submodel list component and autoscrolling to selected AAS

### LINKED ISSUE #86: [FEATURE] "Jumping" to an AAS should reveal the AAS in the AAS list
**Is your feature request related to a problem? Please describe.**
When "jumping" to an AAS (e.g. either via clicking on an element in a BOM or via using a direct link like `<endpoint>/aas-ui/?aas=<aas-id>`), the AAS is selected in the AAS list (on the left) and the submodels are shown in the submodel list. However, when there are a lot of AASes in the AAS list, it is possible that the highlighted AAS is not in the viewport of the user. As there is no other indicator anywhere on the page that shows e.g. the name of the currently displayed AAS, it is not possible to recognize which AAS is actually opened (unless one scrolls through the list of AASes in the AAS list until one finds the highlighted one).

**Describe the solution you'd like**
When "jumping" to an AAS, the the AAS list should be automatically scrolled until the selected AAS is in the users viewport. Additionally, there might be another indicator of the currently selected AAS showing e.g. its name. This could for example be placed at the top of the submodel list.

### PR DESCRIPTION
**Pull request by seicke**
## Description of Changes

aas-name-aas-tree-view

## Related Issue

Closes #86 

## BaSyx Configuration for Testing

https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples/BaSyxMinimal

### CODE REVIEW

**Review by aaronzi — CHANGES_REQUESTED** [review]
Thank you for your PR. I noticed that the AAS Name is not shown in the SubmodelList on desktop when in the viewer mode. Could you please add this as well?

**Comment by seicke** [comment]
There is still another bug:
If you open the GUI with aas query parameter, the AAS is selected (in the AAS list), but the name is not shown in the AASTreeView/SubmodelList.

**Comment by aaronzi** [comment]
You are right, good find. I will try to fix this.

**Comment by seicke** [comment]
Right, opening the GUI with aas query parameter is resulting in
1. dispatchingSelectedAAS as object only containing the endpoint (via AASList.vue | mounted())
2. dispatchingSelectedAAS as object only containing the endpoint (viaApp.vue)

From my point of view it should be sufficient if [mounted() of AASList.vue](https://github.com/eclipse-basyx/basyx-aas-web-ui/blob/fc2665cf810eac94f97dfb2ea5cde43690ccb547/aas-web-ui/src/components/AppNavigation/AASList.vue#L324) will dispatch not just the endpoint of the AAS:

**Review by aaronzi — APPROVED** [review]

**Pull request merged**
