### PR TITLE
Fixes indefinite loading of AAS Treeview after invalid selection

### LINKED ISSUE #20: [BUG] Indefinite loading state of treeview after invalid selection
**Describe the bug**
When selecting an AAS from the AAS List and an error occurs, the loading state never ends.
This prevents the user from selecting another (valid) AAS. The only fix is to reload the UI with the base path (the id of the invalid AAS has to be removed from the URL).

**To Reproduce**
1. Enter an invalid URL (e.g. http://localhost:3000/?aas=http://localhost:8081/shells/aHR0cHM6Ly93d3cudW5pYncuZGUvaWQvc2Nod2luZGVn)
2. See expected error
3. try to click on other (valid) AAS
4. See error saying `Please wait for the current Request to finish.`

**Expected behavior**
The error occurs and afterwards the loading state should end and give the user the option to click on another AAS.

**BaSyx (please complete the following information):**
- BaSyx Version: v2.0
- BaSyx SDK: Java
- AAS Version: DotAAS V3

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by aaronzi**
# Fixes indefinite loading state of AAS Treeview after invalid AAS selection

## Description of Changes

This PR adds missing resets of the loading state of the treeview in the cases were an error is catched or a validation was not successfull.

## Related Issue

Closes #20

### CODE REVIEW

**Comment by seicke** [comment]
I think the loading state should also be reset for retrieving Submodel References in [SubmodelList.vue](https://github.com/eclipse-basyx/basyx-aas-web-ui/blob/main/aas-web-ui/src/components/SubmodelList.vue) (AAS Viewer)

**Review by seicke — CHANGES_REQUESTED** [review]
I think the loading state should also be reset for retrieving Submodel References in [SubmodelList.vue](https://github.com/eclipse-basyx/basyx-aas-web-ui/blob/main/aas-web-ui/src/components/SubmodelList.vue) (AAS Viewer)

**Comment by aaronzi** [comment]
Good point, I totally overlooked that. Thank you very much for the review.

**Review by seicke — APPROVED** [review]
LGTM

**Pull request merged**
